from allennlp.models.span_srl.semi_crf_srl import SemiCrfSemanticRoleLabeler
from allennlp.models.span_srl.frame_semi_crf_srl import FrameSemanticRoleLabeler
from allennlp.models.span_srl.scaffolding.constit_labeler import ConstitLabeler
from allennlp.models.span_srl.scaffolded_frame_srl import ScaffoldedFrameSrl